// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSMAP47QoHvteIqh2-PE0f3ES8vrrOIdg',
    appId: '1:577628540410:web:6f3ce282950af5a6e2e843',
    messagingSenderId: '577628540410',
    projectId: 'khulasah-prod',
    authDomain: 'khulasah-prod.firebaseapp.com',
    storageBucket: 'khulasah-prod.firebasestorage.app',
    measurementId: 'G-QB6QM1ZLSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaADqcZxiKlPcgtTB6m9OBFULxhZuoRs8',
    appId: '1:577628540410:android:53ed5518e7181ee1e2e843',
    messagingSenderId: '577628540410',
    projectId: 'khulasah-prod',
    storageBucket: 'khulasah-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfeX-lrUQvHJTJlSJShvl5WejI78A95v4',
    appId: '1:577628540410:ios:a00f302bd8ef7fc3e2e843',
    messagingSenderId: '577628540410',
    projectId: 'khulasah-prod',
    storageBucket: 'khulasah-prod.firebasestorage.app',
    iosBundleId: 'com.example.khulasahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfeX-lrUQvHJTJlSJShvl5WejI78A95v4',
    appId: '1:577628540410:ios:a00f302bd8ef7fc3e2e843',
    messagingSenderId: '577628540410',
    projectId: 'khulasah-prod',
    storageBucket: 'khulasah-prod.firebasestorage.app',
    iosBundleId: 'com.example.khulasahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSMAP47QoHvteIqh2-PE0f3ES8vrrOIdg',
    appId: '1:577628540410:web:d27df0ff86470435e2e843',
    messagingSenderId: '577628540410',
    projectId: 'khulasah-prod',
    authDomain: 'khulasah-prod.firebaseapp.com',
    storageBucket: 'khulasah-prod.firebasestorage.app',
    measurementId: 'G-JZ12T0397G',
  );
}
